services:
  postgres:
    image: pgvector/pgvector:pg15
    container_name: landit_postgres
    environment:
      POSTGRES_DB: landit_db
      POSTGRES_USER: landit_user
      POSTGRES_PASSWORD: landit_secure_2024
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    restart: unless-stopped

volumes:
  postgres_data: